### PR TITLE
LPS-76631 Template Context contributors do not work in Web Content templates

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @shuyangzhou 

I'm sending you this pull request following @ealonso ' s suggestion https://github.com/liferay/com-liferay-journal/pull/568#issuecomment-353931917

Could you please check this solution in respect of performance?

Thank you very much!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Hey @shuyangzhou 

I was wondering if you could find time to check the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by shuyangzhou** [comment]
@slnn please run a performance regression test for journal on this.

**Comment by slnn** [comment]
@shuyangzhou, will test it and update test results as soon as possible.

**Comment by slnn** [comment]
Here are test results for journal:

Portal Version | Git Id |Session Count  | Meantime of Log in | Meantime of View Page
------------ | ------------- | ------------- | ------------- | -------------
Base Line| f5d0e0e| 68465| 481| 168
https://github.com/shuyangzhou/com-liferay-journal/pull/64 | -| 67713| 524| 182

**Comment by IstvanD** [comment]
Hi @slnn thank you for performing the tests!

**Comment by ealonso** [comment]
Hey @shuyangzhou,

What do you thing about test results? Is it good enough? Can we proceed to merge it?

Regards,
Eudaldo.

**Comment by shuyangzhou** [comment]
See https://github.com/liferay/com-liferay-journal/pull/583
Thanks guys!

**Pull request closed without merging**
